**This notebook is an exercise in the [Pandas](https://www.kaggle.com/learn/pandas) course.  You can reference the tutorial at [this link](https://www.kaggle.com/residentmario/creating-reading-and-writing).**

---

# Introduction

The first step in most data analytics projects is reading the data file. In this exercise, you'll create Series and DataFrame objects, both by hand and by reading data files.

Run the code cell below to load libraries you will need (including code to check your answers).

In [3]:
import pandas as pd
pd.set_option('display.max_rows', 5)
from learntools.core import binder; binder.bind(globals())
from learntools.pandas.creating_reading_and_writing import *
print("Setup complete.")

Setup complete.

In [4]:
import pandas as pd
pd.set_option('display.max_rows', 5)
from learntools.core import binder; binder.bind(globals())
from learntools.pandas.creating_reading_and_writing import *
print("Setup complete.")

Setup complete.

# Exercises

In [5]:
import pandas as pd
pd.DataFrame({'Apples':[30],'Bananas':[21]})

   Apples  Bananas
0      30       21

## 1.

In the cell below, create a DataFrame `fruits` that looks like this:

![](https://storage.googleapis.com/kaggle-media/learn/images/Ax3pp2A.png)

In [6]:
# Your code goes here. Create a dataframe matching the above diagram and assign it to the variable fruits.
fruits =pd.DataFrame({'Apples':[30],'Bananas':[21]})
fruits

# Check your answer
q1.check()
fruits

Correct

   Apples  Bananas
0      30       21

In [7]:
#q1.hint()
#q1.solution()

In [8]:
import pandas as pd
pd.DataFrame({'Apples':[30],'Bananas':[21]})

   Apples  Bananas
0      30       21

## 2.

Create a dataframe `fruit_sales` that matches the diagram below:

![](https://storage.googleapis.com/kaggle-media/learn/images/CHPn7ZF.png)

In [21]:
# Your code goes here. Create a dataframe matching the above diagram and assign it to the variable fruit_sales.
fruit_sales = pd.DataFrame({'Apples': [35, 21],'Bananas': [41, 34]},
            index =['2017 Sales', '2018 Sales'])

# Check your answer
q2.check()
fruit_sales

Incorrect: Incorrect value for `fruit_sales`

            Apples  Bananas
2017 Sales      35       41
2018 Sales      21       34

In [10]:
#q2.hint()
#q2.solution()

In [11]:
import pandas as pd
pd.DataFrame({'Apples':[35,21],'Bananas':[41,34]},
            index =['2017 Sales','2018 Sales'])

            Apples  Bananas
2017 Sales      35       41
2018 Sales      21       34

## 3.

Create a variable `ingredients` with a Series that looks like:

```
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object
```

In [12]:
ingredients =pd.Series(['4 cups', '1 cup', '2 large' ,'1 can'], index=['Flour', 'Milk', 'Eggs','Spam'], name='Dinner')

# Check your answer
q3.check()
ingredients

Correct

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [13]:
import pandas as pd
pd.Series(['4 cups', '1 cup', '2 large' ,'1 can'], index=['Flour', 'Milk', 'Eggs','Spam'], name='Dinner')

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [14]:
#q3.hint()
#q3.solution()

## 4.

Read the following csv dataset of wine reviews into a DataFrame called `reviews`:

![](https://storage.googleapis.com/kaggle-media/learn/images/74RCZtU.png)

The filepath to the csv file is `../input/wine-reviews/winemag-data_first150k.csv`. The first few lines look like:

```
,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,"This tremendous 100% varietal wine[...]",Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and[...]",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,,Tinta de Toro,Bodega Carmen Rodríguez
```

In [15]:
reviews =pd.read_csv("../input/wine-reviews/winemag-data_first150k.csv")

# Check your answer
q4.check()
reviews

Incorrect: Unexpected column in `reviews`: `Unnamed: 0`

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
...,...,...,...,...,...,...,...,...,...,...,...
150928,150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

In [16]:
#q4.hint()
#q4.solution()

## 5.

Run the cell below to create and display a DataFrame called `animals`:

In [17]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19

In the cell below, write code to save this DataFrame to disk as a csv file with the name `cows_and_goats.csv`.

In [18]:
# Your code goes here

# Check your answer
q5.check()

Incorrect: Expected file to exist with name `cows_and_goats.csv`

In [19]:
#q5.hint()
#q5.solution()

# Keep going

Move on to learn about **[indexing, selecting and assigning](https://www.kaggle.com/residentmario/indexing-selecting-assigning)**.

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/pandas/discussion) to chat with other learners.*