**This notebook is an exercise in the [Pandas](https://www.kaggle.com/learn/pandas) course.  You can reference the tutorial at [this link](https://www.kaggle.com/residentmario/data-types-and-missing-values).**

---

# Introduction

Run the following cell to load your data and some utility functions.

In [1]:
import pandas as pd

reviews = pd.read_csv("../input/wine-reviews/winemag-data-130k-v2.csv", index_col=0)

from learntools.core import binder; binder.bind(globals())
from learntools.pandas.data_types_and_missing_data import *
print("Setup complete.")

Setup complete.

# Exercises

## 1. 
What is the data type of the `points` column in the dataset?

In [2]:
points_dtype = reviews['points'].dtype

# Print the data type
points_dtype

dtype('int64')

In [ ]:
#q1.hint()
#q1.solution()

## 2. 
Create a Series from entries in the `points` column, but convert the entries to strings. Hint: strings are `str` in native Python.

In [3]:
points_as_strings = reviews['points'].astype(str)

# Print the resulting Series
points_as_strings

0         87
1         87
2         87
3         87
4         87
          ..
129966    90
129967    90
129968    90
129969    90
129970    90
Name: points, Length: 129971, dtype: object

In [ ]:
#q2.hint()
#q2.solution()

## 3.
Sometimes the price column is null. How many reviews in the dataset are missing a price?

In [4]:
missing_price_count = reviews['price'].isnull().sum()

# Print the count
missing_price_count

8996

In [ ]:
#q3.hint()
#q3.solution()

## 4.
What are the most common wine-producing regions? Create a Series counting the number of times each value occurs in the `region_1` field. This field is often missing data, so replace missing values with `Unknown`. Sort in descending order.  Your output should look something like this:

```
Unknown                    21247
Napa Valley                 4480
                           ...  
Bardolino Superiore            1
Primitivo del Tarantino        1
Name: region_1, Length: 1230, dtype: int64
```

In [5]:
reviews['region_1'] = reviews['region_1'].fillna('Unknown')

# Create the common_regions Series
common_regions = reviews['region_1'].value_counts().sort_values(ascending=False)

# Print the resulting Series
common_regions

region_1
Unknown                 21247
Napa Valley              4480
Columbia Valley (WA)     4124
Russian River Valley     3091
California               2629
                        ...
Offida Rosso                1
Corton Perri√®res            1
Isle St. George             1
Geelong                     1
Paestum                     1
Name: count, Length: 1230, dtype: int64

In [ ]:
#q4.hint()
#q4.solution()

# Keep going

Move on to **[renaming and combining](https://www.kaggle.com/residentmario/renaming-and-combining)**.

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/pandas/discussion) to chat with other learners.*